### ISSUE TITLE
blender -> blender

### ISSUE THREAD

**Issue by relrod** [benbalter/open-source-alternatives#1]
http://benbalter.github.com/open-source-alternatives/#3dmodelling

"Software: Blender" -> "Consider as Alternative to: Blender"

What? :-)

**Comment by awilfox** [comment]
Trying to use Blender is about as confusing as that, but yes, I noticed this.  Some suggestions would be 3ds Max, Cinema 4D, and LightWave 3D.

**Comment by benbalter** [comment]
Thanks for the feedback. ca4c97a should now include your suggestions.
